eureka:
    client:
        service-url:
            default-zone: http//:localhost:8176/eureka
server:
    port: 8000
spring:
    application:
        name: currecy-exchange-service
    config:
        import: optional:configserver:http://localhost:8888
    data:
        jpa:
            repositories:
                bootstrap-mode: default
    datasource:
        url: jdbc:h2:mem:testdb;
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        defer-datasource-initialization: true
